# Generated by Django 4.0.1 on 2022-01-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='party_size',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '3'), (6, '4'), (8, '8')]),
        ),
    ]
