# Generated by Django 4.0.1 on 2022-01-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_table_party_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='available_time',
        ),
    ]
