# Generated by Django 4.0.1 on 2022-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_table_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='party_size',
            field=models.IntegerField(),
        ),
    ]
