# Generated by Django 4.0.1 on 2022-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_table_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='customer',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
